# Generated by Django 3.0.6 on 2020-07-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('floor', models.IntegerField(default=1)),
                ('room_number', models.IntegerField(default=1)),
                ('capacity', models.IntegerField(default=1)),
            ],
        ),
    ]
